version: 2.1

.test_python_steps: &test_python_steps
  - checkout
  - run: "${SUDO_COMMAND}pip install -r requirements.txt -r test-requirements.txt"
  - run: pytest -v --cov=ethtool_exporter --cov-fail-under=92
  - run: python ethtool_exporter.py --help

environment:
  SUDO_COMMAND: ""

jobs:
  test_python_3_6:
    environment:
      SUDO_COMMAND: "sudo "
    docker:
      - image: circleci/python:3.6
    steps: *test_python_steps
  test_python_3_7:
    environment:
      SUDO_COMMAND: "sudo "
    docker:
      - image: circleci/python:3.7
    steps: *test_python_steps
  test_python_3_8:
    environment:
      SUDO_COMMAND: "sudo "
    docker:
      - image: circleci/python:3.8
    steps: *test_python_steps
  test_python_3_9:
    environment:
      SUDO_COMMAND: "sudo "
    docker:
      - image: circleci/python:3.9
    steps: *test_python_steps
  test_python_3_10:
    environment:
      SUDO_COMMAND: "sudo "
    docker:
      - image: circleci/python:3.10
    steps: *test_python_steps
  test_python_3_11:
    docker:
      - image: cimg/python:3.11.4
    steps: *test_python_steps
workflows:
  main:
    jobs:
      - test_python_3_6
      - test_python_3_7
      - test_python_3_8
      - test_python_3_9
      - test_python_3_10
      - test_python_3_11
